# Generated by Django 5.1.4 on 2024-12-06 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='top_phrases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='word_frequency',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transcription',
            constraint=models.UniqueConstraint(fields=('user', 'audio_file'), name='unique_audio_per_user'),
        ),
    ]
