# Generated by Django 5.1.4 on 2024-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer1', '0003_remove_transcription_unique_audio_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='similarity_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
