# Generated by Django 5.1.4 on 2024-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer1', '0005_transcription_detected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='target_language',
            field=models.CharField(blank=True, default='en', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='detected_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
