# Generated by Django 5.1.4 on 2024-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer1', '0006_transcription_target_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
